<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>${anypoint.groupId}</groupId>
	<!-- <groupId>aa698b83-e3f6-4a0c-a0cb-35c2c4639454</groupId> -->
	<artifactId>mule-datablind-connector</artifactId>
	<version>5.0.15</version>
	<packaging>mule-extension</packaging>
	<name>dblconnector_j17</name>

	<properties>
		<munit.input.directory>src/test/munit</munit.input.directory>
		<munit.output.directory>${basedir}/target/test-mule/munit</munit.output.directory>
		<munit.extensions.maven.plugin.version>1.6.1</munit.extensions.maven.plugin.version>
		<munit.version>3.6.3</munit.version>
		<maven.resources.plugin.version>3.3.1</maven.resources.plugin.version>
		<anypoint.groupId>13c7cbe2-61a5-4740-9da0-ae298639b607</anypoint.groupId>
	  </properties>

	<parent>
		<groupId>org.mule.extensions</groupId>
		<artifactId>mule-modules-parent</artifactId>
		<version>1.9.7</version>
	</parent>
	
	<dependencies>
		<dependency>
			<groupId>org.mule.sdk</groupId>
			<artifactId>mule-sdk-api</artifactId>
			<version>0.12.0</version>
		</dependency>
		<dependency>
			<groupId>com.ztensor</groupId>
			<artifactId>datacrypt-release</artifactId>
			<version>3.0.7</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>${maven.resources.plugin.version}</version>
				<executions>
					<execution>
						<id>copy-munit-resources</id>
						<phase>process-test-resources</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${munit.output.directory}</outputDirectory>
							<resources>
								<resource>
									<directory>${munit.input.directory}</directory>
									<filtering>true</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.mulesoft.munit</groupId>
				<artifactId>munit-extensions-maven-plugin</artifactId>
				<version>${munit.extensions.maven.plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>test</goal>
						</goals>
						<phase>integration-test</phase>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>com.mulesoft.munit</groupId>
						<artifactId>munit-runner</artifactId>
						<version>${munit.version}</version>
						<classifier>mule-plugin</classifier>
					</dependency>
					<dependency>
						<groupId>com.mulesoft.munit</groupId>
						<artifactId>munit-tools</artifactId>
						<version>${munit.version}</version>
						<classifier>mule-plugin</classifier>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.2.5</version>
				<configuration>
					<argLine>-Djdk.net.URLClassPath.disableClassPathURLCheck=true</argLine>
					<useModulePath>false</useModulePath>
					<useSystemClassLoader>false</useSystemClassLoader>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.14</version>
				<executions>
					<execution>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	
	<repositories>
		<repository>
			<id>datablindrepo</id>
			<name>GitHub OWNER Apache Maven Packages</name>
			<url>https://maven.pkg.github.com/datablind/datacrypt-release</url>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
		</repository>
	</repositories>
	<distributionManagement>
		<!-- 
          In order to publish to the Exchange make sure the the user id has 
		  all the following scopes:
		  - Exchange Contributor
		  - Exchange Creator
		  - Exchange Viewer
		  - Design Center Developer
	    -->
		<snapshotRepository>
			<id>exchange-server</id>
			<name>Exchange Repository</name>
			<url>https://maven.anypoint.mulesoft.com/api/v2/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
			<releases>
				<checksumPolicy>ignore</checksumPolicy>
			</releases>
		</snapshotRepository>

		<repository>
			<id>anypoint-exchange</id>
			<name>Exchange Repository</name>
			<url>https://maven.anypoint.mulesoft.com/api/v2/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
			<releases>
				<checksumPolicy>ignore</checksumPolicy>
			</releases>
		</repository>
	</distributionManagement>
</project>
