<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>org.ztensor.connectors</groupId>
	<artifactId>mule-datablind-connector</artifactId>
	<version>5.0.20</version>
	<packaging>mule-extension</packaging>
	<name>DataBlind Connector - Mule 4</name>

	<properties>
		<munit.input.directory>src/test/munit</munit.input.directory>
		<munit.output.directory>${basedir}/target/test-mule/munit</munit.output.directory>
		<munit.extensions.maven.plugin.version>1.6.1</munit.extensions.maven.plugin.version>
		<munit.version>3.6.3</munit.version>
		<maven.resources.plugin.version>3.3.1</maven.resources.plugin.version>
		<jacoco.version>0.8.14</jacoco.version>
        <!-- <maven.surefire.version>2.22.2</maven.surefire.version> -->
		<maven.surefire.version>3.5.4</maven.surefire.version>
	  </properties>

	<parent>
		<groupId>org.mule.extensions</groupId>
		<artifactId>mule-modules-parent</artifactId>
		<version>1.9.7</version>
	</parent>
	
	<dependencies>
		<dependency>
			<groupId>org.mule.sdk</groupId>
			<artifactId>mule-sdk-api</artifactId>
			<version>0.12.0</version>
		</dependency>
		<dependency>
			<groupId>com.ztensor</groupId>
			<artifactId>datacrypt</artifactId>
			<version>3.0.8</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>${maven.resources.plugin.version}</version>
				<executions>
					<execution>
						<id>copy-munit-resources</id>
						<phase>process-test-resources</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${munit.output.directory}</outputDirectory>
							<resources>
								<resource>
									<directory>${munit.input.directory}</directory>
									<filtering>true</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.mulesoft.munit</groupId>
				<artifactId>munit-extensions-maven-plugin</artifactId>
				<version>${munit.extensions.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<argLines>
							<argLine>
									-javaagent:${settings.localRepository}/org/jacoco/org.jacoco.agent/${jacoco.version}/org.jacoco.agent-${jacoco.version}-runtime.jar=destfile=${session.executionRootDirectory}/target/jacoco.exec
							</argLine>
					</argLines>
					<sharedLibraries>
							<sharedLibrary>
									<groupId>org.jsoup</groupId>
									<artifactId>jsoup</artifactId>
							</sharedLibrary>
					</sharedLibraries>
			    </configuration>
				<executions>
					<execution>
						<goals>
							<goal>test</goal>
						</goals>
						<phase>integration-test</phase>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>com.mulesoft.munit</groupId>
						<artifactId>munit-runner</artifactId>
						<version>${munit.version}</version>
						<classifier>mule-plugin</classifier>
					</dependency>
					<dependency>
						<groupId>com.mulesoft.munit</groupId>
						<artifactId>munit-tools</artifactId>
						<version>${munit.version}</version>
						<classifier>mule-plugin</classifier>
					</dependency>
					<dependency>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>${jacoco.version}</version>
				    </dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire.version}</version>
				<configuration>
						<argLine>-Dfile.encoding=UTF-8</argLine>
						<argLine>
								-javaagent:${settings.localRepository}/org/jacoco/org.jacoco.agent/${jacoco.version}/org.jacoco.agent-${jacoco.version}-runtime.jar=destfile=${session.executionRootDirectory}/target/jacoco.exec
						</argLine>
				</configuration>
				<dependencies>
						<dependency>
								<groupId>org.jacoco</groupId>
								<artifactId>jacoco-maven-plugin</artifactId>
								<version>${jacoco.version}</version>
						</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${jacoco.version}</version>
				<executions>
						<execution>
								<id>jacoco-initialize</id>
								<goals>
										<goal>prepare-agent</goal>
								</goals>
						</execution>
						<execution>
								<id>jacoco-site</id>
								<phase>verify</phase>
								<goals>
										<goal>report</goal>
								</goals>
						</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	
	<repositories>
		<repository>
			<id>datablindrepo</id>
			<name>GitHub OWNER Apache Maven Packages</name>
			<url>https://maven.pkg.github.com/datablind/datacrypt-release</url>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
		</repository>
		<!-- <repository>
			<id>MuleRepository</id>
			<name>MuleRepository</name>
			<url>https://repository.mulesoft.org/nexus-domain/content/repositories/releases-ee/</url>
		</repository> -->
	</repositories>
	<!-- <distributionManagement>
		
          In order to publish to the Exchange make sure the the user id has 
		  all the following scopes:
		  - Exchange Contributor
		  - Exchange Creator
		  - Exchange Viewer
		  - Design Center Developer
	    
		<snapshotRepository>
			<id>exchange-server</id>
			<name>Exchange Repository</name>
			<url>https://maven.anypoint.mulesoft.com/api/v2/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
			<releases>
				<checksumPolicy>ignore</checksumPolicy>
			</releases>
		</snapshotRepository>

		<repository>
			<id>anypoint-exchange</id>
			<name>Exchange Repository</name>
			<url>https://maven.anypoint.mulesoft.com/api/v2/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
			<releases>
				<checksumPolicy>ignore</checksumPolicy>
			</releases>
		</repository>
	</distributionManagement> -->
</project>
